

---
- name: Example clone of a single branch
  ansible.builtin.git:
     repo: https://github.com/bradtraversy/myflaskapp.git
     dest: /home/damon/test
     single_branch: yes
     version: master
